### ISSUE TITLE
googleapi: Error 412: Precondition Failed, conditionNotMet

### ISSUE THREAD

**Issue by naseemkullah** [GoogleCloudPlatform/gke-autoneg-controller#4]
Hi,
I am getting the following error with autoneg controller.
Any idea what the missing precondition could be?

```
autoneg-controller-manager manager 2019-12-10T19:58:09.561Z    INFO    controllers.Service     Applying intended status        {"service": "foo/bar", "status": {"name":"bar","max_rate_per_endpoint":1000,"network_endpoint_groups":{"80":"k8s1-foo-bar-80-12345a"},"zones":["us-central1-a"]}}
autoneg-controller-manager manager 2019-12-10T19:58:09.990Z    ERROR   controller-runtime.controller   Reconciler error        {"controller": "service", "request": "foo/bar", "error": "googleapi: Error 412: Precondition Failed, conditionNotMet"}
```

A backend service named `bar` exists in the project, it has 0 backends at this time.

cc @soellman  🙏

**Comment by soellman** [comment]
Hi Naseem - this error code is misleading, and may indicate that there is another, underlying error. I suspect that the service account you have doesn't have the all the permissions required.

I just pushed up a commit with new instructions to create an IAM role with all the required permissions (for use with Workload Identity). Would you try that and see if it resolves your issue?

**Comment by naseemkullah** [comment]
Hi @soellman - with the updated permissions it seems to be working, thanks!

FWIW i've used Terraform as follows:

```
data "google_project" "project" {
}

resource "google_service_account" "autoneg_controller" {
  account_id   = "autoneg-controller"
  display_name = "TF managed service account for autoneg-controller"
}

resource "google_project_iam_custom_role" "autoneg_controller" {
  role_id     = "autonegController"
  title       = "GKE Autoneg Controller"
  description = "Updates backend services based on NEGs in GKE"
  permissions = [
    "compute.backendServices.get",
    "compute.backendServices.update",
    "compute.networkEndpointGroups.use",
    "compute.healthChecks.useReadOnly",
  ]
}

resource "google_project_iam_binding" "autoneg_controller" {
  project = data.google_project.project.id
  role    = "projects/${data.google_project.project.id}/roles/${google_project_iam_custom_role.autoneg_controller.role_id}" # "roles/compute.loadBalancerAdmin"
  members = [
    "serviceAccount:${google_service_account.autoneg_controller.email}",
  ]
}

resource "google_service_account_iam_binding" "autoneg_controller_workload_identity" {
  service_account_id = google_service_account.autoneg_controller.name
  role               = "roles/iam.workloadIdentityUser"
  members = [
    "serviceAccount:${data.google_project.project.id}.svc.id.goog[autoneg-system/autoneg-controller-manager]",
  ]
}

```

**Comment by wsstoregene** [comment]
Hello,

I am incurring in the same issue.

###############
May-01 09:21:14.792 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://bucket-genome-cogos-dev-uk/storegene-data/nextflow-logs/42/5d3fe82c4ce26466f9d9845a0dd110/.command.err
May-01 09:21:14.826 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://bucket-genome-cogos-dev-uk/storegene-data/nextflow-logs/42/5d3fe82c4ce26466f9d9845a0dd110/.command.out
May-01 09:21:14.829 [main] DEBUG nextflow.Session - Session await > all processes finished
May-01 09:21:14.829 [main] DEBUG nextflow.Session - Session await > all barriers passed
May-01 09:21:14.866 [main] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://bucket-genome-cogos-dev-uk/storegene-data/nextflow-logs/42/5d3fe82c4ce26466f9d9845a0dd110/.command.err
May-01 09:21:14.898 [main] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://bucket-genome-cogos-dev-uk/storegene-data/nextflow-logs/42/5d3fe82c4ce26466f9d9845a0dd110/.command.out
May-01 09:21:14.905 [main] WARN  n.processor.TaskPollingMonitor - Killing running tasks (2)
May-01 09:21:14.925 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=2; runningCount=-2; retriesCount=0; abortedCount=2; succeedDuration=0ms; failedDuration=3.9s; cachedDuration=0ms;loadCpus=-2; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
May-01 09:21:14.925 [main] DEBUG nextflow.trace.ReportObserver - Workflow completed -- rendering execution report
May-01 09:21:14.972 [main] DEBUG nextflow.trace.ReportObserver - Execution report summary data:
  [{"cpuUsage":null,"process":"generate_patient_data2","mem":null,"memUsage":null,"timeUsage":null,"vmem":null,"reads":null,"cpu":null,"time":{"mean":3867,"min":3867,"q1":3867,"q2":3867,"q3":3867,"max":3867,"minLabel":"generate_patient_data2 (1)","maxLabel":"generate_patient_data2 (1)","q1Label":"generate_patient_data2 (1)","q2Label":"generate_patient_data2 (1)","q3Label":"generate_patient_data2 (1)"},"writes":null},{"cpuUsage":null,"process":"parse_gvcf","mem":null,"memUsage":null,"timeUsage":null,"vmem":null,"reads":null,"cpu":null,"time":null,"writes":null},{"cpuUsage":null,"process":"get_ref_pos","mem":null,"memUsage":null,"timeUsage":null,"vmem":null,"reads":null,"cpu":null,"time":null,"writes":null}]
May-01 09:21:16.204 [main] WARN  nextflow.trace.ReportObserver - Failed to render execution report -- see the log file for details
com.google.cloud.storage.StorageException: 412 Precondition Failed
PUT https://storage.googleapis.com/upload/storage/v1/b/bucket-genome-cogos-dev-uk/o?ifGenerationMatch=0&name=storegene-data/pipeline-data/templates/75/performance-report/patient/11_202404172326.html&uploadType=resumable&upload_id=ABPtcPoQl66dLPSkFLFS2H7VTpf9pzYCoxr0yX77a9EoglqsnV7DMFotTT4A2vzJEXlBLTNOwsQ1rdNFetn5aoretmR_4RihNSPPzMnGHAj6-h82sw
{
  "error": {
    "code": 412,
    "message": "At least one of the pre-conditions you specified did not hold.",
    "errors": [
      {
        "message": "At least one of the pre-conditions you specified did not hold.",
        "domain": "global",
        "reason": "conditionNotMet",
        "locationType": "header",
        "location": "If-Match"
      }
    ]
  }
}

	at com.google.cloud.storage.StorageException.translate(StorageException.java:118)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:287)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.writeWithResponse(HttpStorageRpc.java:959)
	at com.google.cloud.storage.BlobWriteChannel.transmitChunk(BlobWriteChannel.java:67)
	at com.google.cloud.storage.BlobWriteChannel.access$1400(BlobWriteChannel.java:34)
	at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:183)
	at com.google.cloud.BaseWriteChannel.close(BaseWriteChannel.java:151)
	at com.google.cloud.storage.contrib.nio.CloudStorageWriteChannel.close(CloudStorageWriteChannel.java:55)
	at java.base/java.nio.channels.Channels$1.close(Channels.java:176)
	at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:347)
	at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169)
	at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:252)
	at java.base/java.io.BufferedWriter.close(BufferedWriter.java:269)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withWriter(IOGroovyMethods.java:1141)
	at nextflow.trace.ReportObserver.renderHtml(ReportObserver.groovy:284)
	at nextflow.trace.ReportObserver.onFlowComplete(ReportObserver.groovy:140)
	at nextflow.Session.notifyFlowComplete(Session.groovy:1075)
	at nextflow.Session.shutdown0(Session.groovy:702)
	at nextflow.Session.destroy(Session.groovy:644)
	at nextflow.script.ScriptRunner.shutdown(ScriptRunner.groovy:240)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:135)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:354)
	at nextflow.cli.Launcher.run(Launcher.groovy:487)
	at nextflow.cli.Launcher.main(Launcher.groovy:646)
Caused by: com.google.api.client.http.HttpResponseException: 412 Precondition Failed
PUT https://storage.googleapis.com/upload/storage/v1/b/bucket-genome-cogos-dev-uk/o?ifGenerationMatch=0&name=storegene-data/pipeline-data/templates/75/performance-report/patient/11_202404172326.html&uploadType=resumable&upload_id=ABPtcPoQl66dLPSkFLFS2H7VTpf9pzYCoxr0yX77a9EoglqsnV7DMFotTT4A2vzJEXlBLTNOwsQ1rdNFetn5aoretmR_4RihNSPPzMnGHAj6-h82sw
{
  "error": {
    "code": 412,
    "message": "At least one of the pre-conditions you specified did not hold.",
    "errors": [
      {
        "message": "At least one of the pre-conditions you specified did not hold.",
        "domain": "global",
        "reason": "conditionNotMet",
        "locationType": "header",
        "location": "If-Match"
      }
    ]
  }
}

	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.writeWithResponse(HttpStorageRpc.java:932)
	... 26 common frames omitted

**Comment by rosmo** [comment]
Autoneg doesn't use Cloud Storage for anything, so unlikely it has anything to do with the error.
